version: '3.5'
services:
  php:
    build: docker/php-fpm
    volumes:
      - ./:/var/www/html:cached
      - ./logs:/var/www/var/logs:cached
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 33406:3306
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: somedatabase
      MYSQL_USER: someuser
      MYSQL_PASSWORD: somepassword

  nginx:
    build: docker/nginx
    ports:
      - '8060:80'
    links:
      - php
    volumes:
      - ./:/var/www/html:cached
      - ./logs/nginx/:/var/log/nginx:cached
    depends_on:
      - php
